name: 'docker build'
description: 'Who to greet'
inputs:
  username:
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: composite
  steps:
    - run: |
        echo "Hello World"
      shell: bash