name: 'docker build'
description: 'Who to greet'
inputs:
  path_dockerfile:
    description: 'Dockerfile (optional)'
    required: false
    default: 'Dockerfile'
  image_name:
    description: 'Name of the Docker image'
    required: true
  input_tag:
    description: 'Tag for the Docker image (optional)'
    required: false
runs:
  using: composite
  steps:
    - name: Check for input tag
      run: |
        if [ -z "${{ inputs.input_tag }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.input_tag }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV 
        docker build . --file "${{ inputs.path_dockerfile }}" --tag academy:$(date +%s)
      shell: bash
