name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: joaoribeiro024/academy/.github/actions/docker_build@main
        with:
          input_tag: latest
          image_name: academy
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SECRET_ACADEMY_1 }}
          password: ${{ secrets.SECRET_ACADEMY_2 }}
      - name: Upload docker image
        uses: joaoribeiro024/academy/.github/actions/docker_build_dockerhub@main
        with:
          docker_username: joaoribeiro0go
          image_name: academy
      - name: List docker images
        run: docker images 
        