name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: joaoribeiro024/academy/.github/actions/docker_build@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
    - name: List docker images
      run: docker images 
